Repository maplibre/maplibre-gl-directions, pull requests merged in 2022-07, with the labels that each got.

#110 Restyling docs and examples. Refactoring. Smallfixes. Prep. for v. 1
  demo/src/Menu.svelte
  demo/src/assets/map/custom-directions.ts
  demo/src/assets/map/distance-measurement-directions.ts
  demo/src/assets/map/images/balloon-hoverpoint.png
  demo/src/assets/map/images/balloon-snappoint.png
  demo/src/assets/map/images/balloon-waypoint.png
  demo/src/assets/map/images/routeline.png
  demo/src/assets/map/restyling-example-layers.ts
  demo/src/components/AppSidebar.svelte
  demo/src/examples/10 Restyling.svelte
  demo/src/examples/11 Distance Measurement.svelte
  demo/src/examples/12 Load and Save.svelte
  demo/src/examples/4 Origin and Destination.svelte
  demo/src/examples/5 Show Routes' Directions.svelte
  demo/src/examples/8 Aborting Requests.svelte
  demo/src/router.ts
  doc/BASIC_USAGE.md
  doc/CONTROLS.md
  doc/CUSTOMIZATION.md
  doc/images/complex-customization.png
  src/main.ts
Labels: semver:major

#129 Update dependabot.yml
  .github/dependabot.yml
Labels: release:ignore

#115 Update routes while dragging
  demo/src/examples/1 User Interaction.svelte
  demo/src/examples/3 Mapbox Directions API and Congestions.svelte
  src/directions/main.ts
  src/directions/types.ts
Labels: enhancement, semver:minor
