Repository maplibre/maplibre-gl-directions, pull requests merged in 2022-09, with the labels that each got.

#161 Update deps
  package-lock.json
Labels: release:ignore

#162 Revert "chore(deps-dev): bump typescript from 4.7.4 to 4.8.2 (#151)"
  package-lock.json
  package.json
Labels: release:ignore

#163 Update deps
  package-lock.json
  package.json
Labels: semver:patch, dependencies

#166 Changes to onDragDown
  src/directions/main.ts
Labels: enhancement, semver:patch

#167 Staging
  .github/dependabot.yml
  package-lock.json
  package.json
  src/directions/main.ts
Labels: release:ignore

#170 Fix for github issue 169 ca't drag map
  src/directions/main.ts
Labels: semver:patch

#171 Fix comments
  src/directions/types.ts
Labels: documentation, release:ignore
