Repository maplibre/maplibre-gl-directions, pull requests merged in 2024-01, with the labels that each got.

#216 Feature: Multiple routing profiles
  demo/src/examples/14 Multiple profiles.svelte
  package-lock.json
  package.json
  src/controls/bearings/BearingsControl.svelte
  src/directions/helpers.ts
  src/directions/layers.ts
  src/directions/main.ts
  src/directions/utils.ts
  tsconfig.node.json
  vite.demo.config.ts
Labels: enhancement, semver:minor

#217 Feature: Allow hover effects and route switching in non-interactive mode
  demo/src/examples/1 User Interaction.svelte
  src/directions/main.ts
Labels: enhancement, semver:minor

#218 TS strict mode
  demo/src/components/AppSidebar.svelte
  demo/src/examples/1 User Interaction.svelte
  demo/src/examples/10 Bearings Support and Control.svelte
  demo/src/examples/11 Restyling.svelte
  demo/src/examples/12 Distance Measurement.svelte
  demo/src/examples/13 Load and Save.svelte
  demo/src/examples/14 Multiple profiles.svelte
  demo/src/examples/2 Programmatical Control.svelte
  demo/src/examples/3 Mapbox Directions API and Congestions.svelte
  demo/src/examples/4 Origin and Destination.svelte
  demo/src/examples/5 Show Routes' Directions.svelte
  demo/src/examples/6 Touch-Friendly Features.svelte
  demo/src/examples/7 Events.svelte
  demo/src/examples/8 Aborting Requests.svelte
  demo/src/examples/9 Loading Indicator Control.svelte
  demo/src/main.ts
  demo/src/router.ts
  package.json
  src/controls/bearings/BearingsControl.svelte
  src/directions/events.ts
  src/directions/helpers.ts
  src/directions/layers.ts
  src/directions/main.ts
  src/directions/utils.ts
  src/tsconfig.json
  tsconfig.json
  tsconfig.lib.json
Labels: enhancement, semver:patch

#219 Update the dependencies
  package-lock.json
  package.json
Labels: semver:patch, dependencies

#221 Bug fix: Fixed route line building
  src/directions/utils.ts
Labels: bug, semver:patch
